version: '3.7'
services:
  mysql:
    image: library/postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db